ALTER TABLE minions_info
    ALTER COLUMN age SET NOT NULL,
    ALTER COLUMN age SET DEFAULT 0,
    ALTER COLUMN name SET DEFAULT '',
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN code SET NOT NULL,
    ALTER COLUMN code SET DEFAULT '';
